

# Northwind Basic Sparql Queries


# Selecting all triples
SELECT ?subject ?predicate ?object
WHERE {
  ?subject ?predicate ?object .
}
ORDER BY ?subject


# The query above can be simplified by using * to return all variables,
# short variables names, omit the period and the WHERE clause.
# The compact version will look like the following.
SELECT * {?s ?p ?o} ORDER BY ?s


# Filtering on a predicate
SELECT * {?s :hasProduct ?o} ORDER BY ?s


# Prefixes and namespaces
# The next three queries return the same results

# Selecting product details using URI in the triple pattern
SELECT ?p ?o
WHERE {
  <http://www.mysparql.com/resource/northwind/product-2> ?p ?o .
}


# Selecting product details using a Prefix
PREFIX :<http://www.mysparql.com/resource/northwind/>
SELECT ?p ?o
WHERE {
  :product-2 ?p ?o .
}


# Selecting product details using a database namespace
# An empty prefix must be aded to the database list for this to work.
# In this case the following IRI was added: <http://www.mysparql.com/resource/northwind/>
SELECT ?p ?o
WHERE {
  :product-2 ?p ?o .
}


# Selecting product names
SELECT ?s ?productName
{
    ?s a :Product .
    ?s   :productName ?productName
}


# Note that in the query above the subject is showing twice.
# The subject can be omitted as per below.
SELECT
  ?s
  ?ID
  ?productName
WHERE
{
  ?s a :Product ;
       :productName ?productName ;
       :productID ?ID .
}


# Selecting the unit price of a product using filter
select ?s ?o
{
	?s a :Product .
    ?s   :unitPrice ?o .
  FILTER (?s=:product-1)
}


# Value lists
SELECT ?x WHERE {
  VALUES ?x { 1 2 3 4 }
} 